networks:
  frontend:
    external: true
  backend:

services:
  nginx-prod:
    build: ./docker/nginx/prod
    volumes:
      - ./docker/logs/nginx:/var/log/nginx
      - .:/var/www/catalog
    environment:
      - VIRTUAL_HOST=catalog.test
    ports:
      - "8091:8090"
    networks:
      frontend:
      backend:
        aliases:
          - catalog.test

  php:
    build: ./docker/php
    container_name: php_catalog
    networks:
      - backend
    environment:
      - COMPOSER_MEMORY_LIMIT=2G
      - XDEBUG_SESSION="PHPSTORM"
    volumes:
      - .:/var/www/catalog
      - ./storage/logs:/var/log/php
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini

  postgres:
    image: postgres:latest
    networks:
      frontend:
      backend:
    ports:
      - '5436:5432'
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./docker/postgres/catalog:/var/lib/postgresql/data

  redis:
    image: bitnami/redis:latest
    networks:
      - backend
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}

  supervisor:
      build: ./docker/supervisor
      container_name: supervisor_catalog
      networks:
          - backend
      volumes:
          - .:/var/www/catalog
          - ./storage/logs:/var/log/php
          - ./docker/php/php.ini:/usr/local/etc/php/php.ini
          - ./docker/php/opcache.ini:/usr/local/etc/php/conf.d/opcache.ini

  rabbitmq:
      image: rabbitmq:3-management-alpine
      ports:
          - '5678:5672'
          - '15679:15672'
      volumes:
          - ./docker/rabbitmq/data/:/var/lib/rabbitmq/
      networks:
        frontend:
        backend:
          aliases:
            - rabbitmq.catalog.test
