insert into public.catalog_groups (id, name, sl, json_link)
values  (1, 'Ноутбуки', null, 'https://catalog.onliner.by/sdapi/catalog.api/search/notebook?page=1'),
        (2, 'Планшеты', null, 'https://catalog.onliner.by/sdapi/catalog.api/search/tabletpc?page=1'),
        (3, 'Моноблоки', null, 'https://catalog.onliner.by/sdapi/catalog.api/search/monoblock?page=1'),
        (4, 'Компьютеры', null, 'https://catalog.onliner.by/sdapi/catalog.api/search/desktoppc?page=1'),
        (5, 'Мониторы', null, 'https://catalog.onliner.by/sdapi/catalog.api/search/display?page=1'),
        (6, 'Видеокарты', null, 'https://catalog.onliner.by/sdapi/catalog.api/search/videocard?page=1'),
        (7, 'Процессоры', null, 'https://catalog.onliner.by/sdapi/catalog.api/search/cpu?page=1'),
        (8, 'Материнские платы', null, 'https://catalog.onliner.by/sdapi/catalog.api/search/motherboard?page=1'),
        (9, 'Оперативная память', null, 'https://catalog.onliner.by/sdapi/catalog.api/search/dram?page=1'),
        (10, 'Системы охлаждения', null, 'https://catalog.onliner.by/sdapi/catalog.api/search/fan?page=1'),
        (11, 'SSD', null, 'https://catalog.onliner.by/sdapi/catalog.api/search/ssd?page=1'),
        (12, 'Жесткие диски', null, 'https://catalog.onliner.by/sdapi/catalog.api/search/hdd?page=1'),
        (13, 'Корпуса', null, 'https://catalog.onliner.by/sdapi/catalog.api/search/chassis?page=1'),
        (14, 'Блоки питания', null, 'https://catalog.onliner.by/sdapi/catalog.api/search/powersupply?page=1'),
        (15, 'Звуковые карты', null, 'https://catalog.onliner.by/sdapi/catalog.api/search/soundcard?page=1'),
        (16, 'Сетевые адаптеры', null, 'https://catalog.onliner.by/sdapi/catalog.api/search/networkadapter?page=1'),
        (17, 'Принтеры и МФУ', null, 'https://catalog.onliner.by/sdapi/catalog.api/search/printers?page=1'),
        (18, 'Сканеры', null, 'https://catalog.onliner.by/sdapi/catalog.api/search/scanner?page=1'),
        (19, 'Аксессуары для оргтехники', null, 'https://catalog.onliner.by/sdapi/catalog.api/search/officeequip_acs?page=1'),
        (20, 'Графические планшеты', null, 'https://catalog.onliner.by/sdapi/catalog.api/search/tablets?page=1'),
        (21, 'Стилусы и сменные наконечники', null, 'https://catalog.onliner.by/sdapi/catalog.api/search/stylus_pens?page=1'),
        (22, 'Картриджи для принтеров и МФУ', null, 'https://catalog.onliner.by/sdapi/catalog.api/search/cartridges?page=1'),
        (23, 'Мыши', null, 'https://catalog.onliner.by/sdapi/catalog.api/search/mouse?page=1'),
        (24, 'Клавиатуры', null, 'https://catalog.onliner.by/sdapi/catalog.api/search/keyboards?page=1'),
        (25, 'Наборы периферии', null, 'https://catalog.onliner.by/sdapi/catalog.api/search/peripheralkits?page=1'),
        (26, 'Игровые контроллеры и аксессуары', null, 'https://catalog.onliner.by/sdapi/catalog.api/search/controllers?page=1'),
        (27, 'Коврики для мыши', null, 'https://catalog.onliner.by/sdapi/catalog.api/search/mousepad?page=1'),
        (28, 'Внешние накопители', null, 'https://catalog.onliner.by/sdapi/catalog.api/search/externalhdd?page=1'),
        (29, 'USB Flash', null, 'https://catalog.onliner.by/sdapi/catalog.api/search/usbflash?page=1'),
        (30, 'Карты памяти', null, 'https://catalog.onliner.by/sdapi/catalog.api/search/memcards?page=1'),
        (31, 'Боксы для накопителей', null, 'https://catalog.onliner.by/sdapi/catalog.api/search/hddbox?page=1'),
        (32, 'Сетевые накопители (NAS)', null, 'https://catalog.onliner.by/sdapi/catalog.api/search/nas?page=1'),
        (33, 'Оптические приводы', null, 'https://catalog.onliner.by/sdapi/catalog.api/search/optical?page=1'),
        (34, 'Карт-ридеры', null, 'https://catalog.onliner.by/sdapi/catalog.api/search/cardreaders?page=1'),
        (35, 'Роботы-пылесосы', null, 'https://catalog.onliner.by/sdapi/catalog.api/search/robotcleaner?page=1'),
        (36, 'Мобильные телефоны', null, 'https://catalog.onliner.by/sdapi/catalog.api/search/mobile?page=1'),
        (37, 'Умные часы', null, 'https://catalog.onliner.by/sdapi/catalog.api/search/smartwatch?page=1'),
        (38, 'Беспроводные и портативные колонки', null, 'https://catalog.onliner.by/sdapi/catalog.api/search/wspeaker?page=1'),
        (39, 'Портативные зарядные устройства', null, 'https://catalog.onliner.by/sdapi/catalog.api/search/portablecharger?page=1'),
        (40, 'Игровые приставки', null, 'https://catalog.onliner.by/sdapi/catalog.api/search/console?page=1'),
        (41, 'Мультимедиа акустика', null, 'https://catalog.onliner.by/sdapi/catalog.api/search/sound?page=1'),
        (42, '3D-принтеры', null, 'https://catalog.onliner.by/3dprinter'),
        (43, '3D-ручки', null, 'https://catalog.onliner.by/3d_pen'),
        (44, 'Bluetooth-гарнитуры', null, 'https://catalog.onliner.by/bt'),
        (45, 'Blu-ray проигрыватели', null, 'https://catalog.onliner.by/bluray_player'),
        (46, 'CD-проигрыватели', null, 'https://catalog.onliner.by/cd_player'),
        (47, 'DSL-модемы и маршрутизаторы', null, 'https://catalog.onliner.by/dslmodem'),
        (48, 'DVD плееры', null, 'https://catalog.onliner.by/dvd'),
        (49, 'FM-модуляторы', null, 'https://catalog.onliner.by/fmmodulators'),
        (50, 'GPS-навигаторы', null, 'https://catalog.onliner.by/gps'),
        (51, 'GPS-трекеры', null, 'https://catalog.onliner.by/gps_tracker'),
        (52, 'Hi-Fi акустика', null, 'https://catalog.onliner.by/hifisound'),
        (53, 'IP-камеры', null, 'https://catalog.onliner.by/ipcamera'),
        (54, 'USB-хабы и док-станции', null, 'https://catalog.onliner.by/usbhub'),
        (55, 'Wi-Fi и мультирум акустика', null, 'https://catalog.onliner.by/wireless_hifi'),
        (56, 'Автокресла', null, 'https://catalog.onliner.by/childcarseat'),
        (57, 'Автомобильные антенны', null, 'https://catalog.onliner.by/antenforradio'),
        (58, 'Автомобильные видеоплееры и DVD', null, 'https://catalog.onliner.by/portabletvdvd'),
        (59, 'Автомобильные держатели', null, 'https://catalog.onliner.by/carholder'),
        (60, 'Автомобильные диски', null, 'https://catalog.onliner.by/wheel'),
        (61, 'Автомобильные инверторы', null, 'https://catalog.onliner.by/car_inverter'),
        (62, 'Автомобильные компрессоры', null, 'https://catalog.onliner.by/compressor_auto'),
        (63, 'Автомобильные краски, лаки, эмали, грунтовки', null, 'https://catalog.onliner.by/carpaints'),
        (64, 'Автомобильные пылесосы', null, 'https://catalog.onliner.by/car_vacuum_clean'),
        (65, 'Автомобильные шины', null, 'https://catalog.onliner.by/tires'),
        (66, 'Автомобильные шпатлевки и отвердители', null, 'https://catalog.onliner.by/autofiller'),
        (67, 'Автосигнализации', null, 'https://catalog.onliner.by/caralarm'),
        (68, 'Автохимия и автокосметика для кузова', null, 'https://catalog.onliner.by/exterior_carcare'),
        (69, 'Автохимия и автокосметика для салона', null, 'https://catalog.onliner.by/interior_carcare'),
        (70, 'Автохолодильники, термобоксы, термосумки', null, 'https://catalog.onliner.by/arrefrigerator'),
        (71, 'Аккумуляторы для телефонов', null, 'https://catalog.onliner.by/phoneaccum'),
        (72, 'Аккумуляторы и ЗУ для фото/видеотехники', null, 'https://catalog.onliner.by/batteries'),
        (73, 'Автомобильные аккумуляторы', null, 'https://catalog.onliner.by/carbattery'),
        (74, 'Аккумуляторы для ИБП', null, 'https://catalog.onliner.by/ups_battery'),
        (75, 'Аккумуляторы и зарядные устройства для инструмента', null, 'https://catalog.onliner.by/tools_accum'),
        (76, 'Аксессуары для бара', null, 'https://catalog.onliner.by/bar_accessories'),
        (77, 'Аксессуары для велосипеда', null, 'https://catalog.onliner.by/bike_accessories'),
        (78, 'Аксессуары для косметики', null, 'https://catalog.onliner.by/cosmetics_access'),
        (79, 'Аксессуары для крупной бытовой и встраиваемой техники', null, 'https://catalog.onliner.by/largehomeapp_acs'),
        (80, 'Аксессуары для кухонной техники', null, 'https://catalog.onliner.by/kitchen_acs'),
        (81, 'Аксессуары для мойки и ухода за автомобилем', null, 'https://catalog.onliner.by/carwashandcare'),
        (82, 'Аксессуары для пылесосов, пароочистителей', null, 'https://catalog.onliner.by/vacuum_acs'),
        (83, 'Аксессуары для ТВ', null, 'https://catalog.onliner.by/tvaccessory'),
        (84, 'Аксессуары и крепления для экшен-камер', null, 'https://catalog.onliner.by/actioncamera_acs'),
        (85, 'Аксессуары к товарам для красоты и здоровья', null, 'https://catalog.onliner.by/beauty_acs'),
        (86, 'Акустика', null, 'https://catalog.onliner.by/carspeakers'),
        (87, 'Алкотестеры', null, 'https://catalog.onliner.by/breathalyzer'),
        (88, 'Аминокислоты', null, 'https://catalog.onliner.by/amino_acids'),
        (89, 'Антенны беспроводной связи', null, 'https://catalog.onliner.by/wantenna'),
        (90, 'Антибиотики, противомикробные препараты', null, 'https://catalog.onliner.by/antibiotics'),
        (91, 'Антивирусы и безопасность', null, 'https://catalog.onliner.by/antivirus'),
        (92, 'Антигистаминные (противоаллергические) препараты', null, 'https://catalog.onliner.by/allergy_med'),
        (93, 'Антисептики для кожи', null, 'https://catalog.onliner.by/sanitizer'),
        (94, 'Аппараты для сварки труб', null, 'https://catalog.onliner.by/pipe_welding'),
        (95, 'Арматура', null, 'https://catalog.onliner.by/armatura'),
        (96, 'Аудиоинтерфейсы', null, 'https://catalog.onliner.by/audiointerface'),
        (97, 'Аэрогрили', null, 'https://catalog.onliner.by/aerogrill'),
        (98, 'Аэрохоккей, настольный футбол, мини-бильярд', null, 'https://catalog.onliner.by/airhockey'),
        (99, 'Багажники на крышу', null, 'https://catalog.onliner.by/car_racks'),
        (100, 'Бани, купели', null, 'https://catalog.onliner.by/bath'),
        (101, 'Банкетки', null, 'https://catalog.onliner.by/banquettes'),
        (102, 'Банные печи', null, 'https://catalog.onliner.by/bathstove'),
        (103, 'Бассейны', null, 'https://catalog.onliner.by/pool'),
        (104, 'Батарейки, аккумуляторы, зарядные', null, 'https://catalog.onliner.by/battery'),
        (105, 'Батуты', null, 'https://catalog.onliner.by/trampoline'),
        (106, 'Беговелы', null, 'https://catalog.onliner.by/balancebike'),
        (107, 'Беговые дорожки', null, 'https://catalog.onliner.by/treadmills'),
        (108, 'Беседки', null, 'https://catalog.onliner.by/garden_house'),
        (109, 'Бескаркасная мебель', null, 'https://catalog.onliner.by/beanbag'),
        (110, 'Беспроводные маршрутизаторы', null, 'https://catalog.onliner.by/wrouter'),
        (111, 'Бетономешалки', null, 'https://catalog.onliner.by/concrete'),
        (112, 'Биде', null, 'https://catalog.onliner.by/bidet'),
        (113, 'Бильярдные столы', null, 'https://catalog.onliner.by/billiardtable'),
        (114, 'Бинокли, подзорные трубы и приборы ночного видения', null, 'https://catalog.onliner.by/optic'),
        (115, 'Биотуалеты', null, 'https://catalog.onliner.by/biotoilet'),
        (116, 'Блендеры', null, 'https://catalog.onliner.by/blender'),
        (117, 'Блинницы', null, 'https://catalog.onliner.by/crepemaker'),
        (118, 'Бритвенные станки и лезвия', null, 'https://catalog.onliner.by/razorsandblades'),
        (119, 'Брошюровщики', null, 'https://catalog.onliner.by/bindingmachines'),
        (120, 'Бумага и материалы для печати', null, 'https://catalog.onliner.by/photopaper'),
        (121, 'Бумбоксы и магнитолы', null, 'https://catalog.onliner.by/portaudio'),
        (122, 'Бутылки для воды', null, 'https://catalog.onliner.by/water_bottles'),
        (123, 'Вакуумные упаковщики', null, 'https://catalog.onliner.by/vacuummachine'),
        (124, 'Ванночки и аксессуары для купания малышей', null, 'https://catalog.onliner.by/baby_bath'),
        (125, 'Ванны', null, 'https://catalog.onliner.by/bathtub'),
        (126, 'Варочные панели', null, 'https://catalog.onliner.by/hob_cooker'),
        (127, 'Вафельницы', null, 'https://catalog.onliner.by/waffle'),
        (128, 'Веб-камеры', null, 'https://catalog.onliner.by/webcams'),
        (129, 'Велобагажники', null, 'https://catalog.onliner.by/bicyclerack'),
        (130, 'Велозамки', null, 'https://catalog.onliner.by/bikelock'),
        (131, 'Велозапчасти', null, 'https://catalog.onliner.by/bike_parts'),
        (132, 'Велокомпьютеры', null, 'https://catalog.onliner.by/bikecomp'),
        (133, 'Велокресла', null, 'https://catalog.onliner.by/bikeseat'),
        (134, 'Велопокрышки, велокамеры', null, 'https://catalog.onliner.by/bicycle_tires'),
        (135, 'Велоприцепы и буксиры', null, 'https://catalog.onliner.by/bike_trailer'),
        (136, 'Велосипедные насосы, манометры, шланги', null, 'https://catalog.onliner.by/bike_pump'),
        (137, 'Велосипедные фонари', null, 'https://catalog.onliner.by/bike_light'),
        (138, 'Велосипеды', null, 'https://catalog.onliner.by/bike'),
        (139, 'Велотренажеры', null, 'https://catalog.onliner.by/velosimulator'),
        (140, 'Вентиляторы', null, 'https://catalog.onliner.by/blower'),
        (141, 'Вентиляционные решетки', null, 'https://catalog.onliner.by/ventil_grates'),
        (142, 'Весы для новорожденных', null, 'https://catalog.onliner.by/babyscales'),
        (143, 'Вибраторы', null, 'https://catalog.onliner.by/vibrators'),
        (144, 'Виброплиты', null, 'https://catalog.onliner.by/platecompactor'),
        (145, 'Видеодомофоны', null, 'https://catalog.onliner.by/videodoorphone'),
        (146, 'Видеокамеры', null, 'https://catalog.onliner.by/video'),
        (147, 'Видеорегистраторы', null, 'https://catalog.onliner.by/videoregistrator'),
        (148, 'Виниловые полы', null, 'https://catalog.onliner.by/vinyl_floor'),
        (149, 'Виниловые проигрыватели', null, 'https://catalog.onliner.by/turntable'),
        (150, 'Винные шкафы', null, 'https://catalog.onliner.by/wine_cabinets'),
        (151, 'Витамины, минералы', null, 'https://catalog.onliner.by/vitamins'),
        (152, 'Водонагреватели', null, 'https://catalog.onliner.by/waterheater'),
        (153, 'Воздуходувки', null, 'https://catalog.onliner.by/leafblower'),
        (154, 'Вспениватели молока', null, 'https://catalog.onliner.by/milkfrother'),
        (155, 'Вспышки и лампы', null, 'https://catalog.onliner.by/flashes'),
        (156, 'Вытяжки', null, 'https://catalog.onliner.by/hoods'),
        (157, 'Газонокосилки', null, 'https://catalog.onliner.by/mowers'),
        (158, 'Гамаки', null, 'https://catalog.onliner.by/hammock'),
        (159, 'Гантели, штанги, гири', null, 'https://catalog.onliner.by/freeweights'),
        (160, 'Генераторы', null, 'https://catalog.onliner.by/powerstations'),
        (161, 'Гидроаккумуляторы и расширительные баки', null, 'https://catalog.onliner.by/hydroaccum'),
        (162, 'Гидромассажные ванночки', null, 'https://catalog.onliner.by/footbath'),
        (163, 'Гипсокартон', null, 'https://catalog.onliner.by/drywall'),
        (164, 'Гироциклы', null, 'https://catalog.onliner.by/segway'),
        (165, 'Гитарные комбоусилители', null, 'https://catalog.onliner.by/guitarcombo'),
        (166, 'Гитары', null, 'https://catalog.onliner.by/guitar'),
        (167, 'Гладильные доски', null, 'https://catalog.onliner.by/ironingboard'),
        (168, 'Глюкометры', null, 'https://catalog.onliner.by/glucosemeter'),
        (169, 'Граверы', null, 'https://catalog.onliner.by/engraver'),
        (170, 'Гребные тренажеры', null, 'https://catalog.onliner.by/rowingmachines'),
        (171, 'Громкая связь', null, 'https://catalog.onliner.by/carkit'),
        (172, 'Грунтовка', null, 'https://catalog.onliner.by/primer'),
        (173, 'Грунты для растений', null, 'https://catalog.onliner.by/soilforplants'),
        (174, 'Груши, мешки, манекены для бокса и единоборств', null, 'https://catalog.onliner.by/punching_bags'),
        (175, 'Дачные бытовки и хозблоки', null, 'https://catalog.onliner.by/garden_cabin'),
        (176, 'Дачные туалеты', null, 'https://catalog.onliner.by/outdoor_toilet'),
        (177, 'Двигатели', null, 'https://catalog.onliner.by/engine'),
        (178, 'Дезинфицирующие средства', null, 'https://catalog.onliner.by/disinfectant'),
        (179, 'Декоративная косметика для глаз', null, 'https://catalog.onliner.by/eye_makeup'),
        (180, 'Декоративная косметика для губ', null, 'https://catalog.onliner.by/lip_makeup'),
        (181, 'Декоративная косметика для лица', null, 'https://catalog.onliner.by/face_makeup'),
        (182, 'Декоративный камень и кирпич', null, 'https://catalog.onliner.by/decorative_stone'),
        (183, 'Деревообрабатывающие станки', null, 'https://catalog.onliner.by/woodworking'),
        (184, 'Детекторы валют', null, 'https://catalog.onliner.by/currencydetector'),
        (185, 'Детские автотреки, трассы', null, 'https://catalog.onliner.by/race_track'),
        (186, 'Детские велосипеды', null, 'https://catalog.onliner.by/kidsbike'),
        (187, 'Детские железные дороги', null, 'https://catalog.onliner.by/kidsrailroad'),
        (188, 'Детские комоды', null, 'https://catalog.onliner.by/babydresser'),
        (189, 'Детские кроватки', null, 'https://catalog.onliner.by/babycotbed'),
        (190, 'Детские куклы', null, 'https://catalog.onliner.by/doll'),
        (191, 'Детские парты, столы, стулья', null, 'https://catalog.onliner.by/kidsdesk'),
        (192, 'Детские шезлонги и качалки', null, 'https://catalog.onliner.by/babyswing'),
        (193, 'Диагностические тепловизоры и пирометры', null, 'https://catalog.onliner.by/thermal_imaging'),
        (194, 'Диваны', null, 'https://catalog.onliner.by/divan'),
        (195, 'Диктофоны', null, 'https://catalog.onliner.by/voicerecorder'),
        (196, 'Динамометрические ключи и отвертки', null, 'https://catalog.onliner.by/torque_wrenches'),
        (197, 'Дозаторы, диспенсеры', null, 'https://catalog.onliner.by/dispenser'),
        (198, 'Док-станции для смартфонов', null, 'https://catalog.onliner.by/speakerdock'),
        (199, 'Домкраты', null, 'https://catalog.onliner.by/carjack'),
        (200, 'Дровоколы', null, 'https://catalog.onliner.by/logsplitter'),
        (201, 'Дровяные камины, печи-камины, порталы', null, 'https://catalog.onliner.by/stove'),
        (202, 'Духовые шкафы', null, 'https://catalog.onliner.by/oven_cooker'),
        (203, 'Душевые кабины', null, 'https://catalog.onliner.by/showerbox'),
        (204, 'Душевые панели и гарнитуры', null, 'https://catalog.onliner.by/shower'),
        (205, 'Душевые поддоны', null, 'https://catalog.onliner.by/shower_trays'),
        (206, 'Елки', null, 'https://catalog.onliner.by/tree'),
        (207, 'Елочные игрушки, украшения', null, 'https://catalog.onliner.by/christmasdecor'),
        (208, 'Женские электробритвы и эпиляторы', null, 'https://catalog.onliner.by/ladyshaver'),
        (209, 'Заварочные чайники, кофеварки, френч-прессы', null, 'https://catalog.onliner.by/teapot'),
        (210, 'Зажигалки', null, 'https://catalog.onliner.by/cigarettelighter'),
        (211, 'Заточные станки (точила)', null, 'https://catalog.onliner.by/benchgrinder'),
        (212, 'Звуко- и виброизоляция помещений', null, 'https://catalog.onliner.by/soundproofing'),
        (213, 'Звукосниматели и тонармы', null, 'https://catalog.onliner.by/turntableaccess'),
        (214, 'Зонты', null, 'https://catalog.onliner.by/umbrella'),
        (215, 'Зонты садовые, пляжные', null, 'https://catalog.onliner.by/street_umbrella'),
        (216, 'Зубные щетки и ирригаторы', null, 'https://catalog.onliner.by/toothbrush'),
        (217, 'Игровые домики и палатки', null, 'https://catalog.onliner.by/playhouse'),
        (218, 'Игрушечный транспорт', null, 'https://catalog.onliner.by/toy_cars'),
        (219, 'Игры для ПК', null, 'https://catalog.onliner.by/pcgames'),
        (220, 'Игры для приставок', null, 'https://catalog.onliner.by/games'),
        (221, 'Игры-опыты, эксперименты', null, 'https://catalog.onliner.by/science_kits'),
        (222, 'Измельчители (чопперы)', null, 'https://catalog.onliner.by/chopper'),
        (223, 'Измельчители пищевых отходов', null, 'https://catalog.onliner.by/disposer'),
        (224, 'Ингаляторы', null, 'https://catalog.onliner.by/inhaler'),
        (225, 'Инсталляции для унитазов, раковин, биде и писсуаров', null, 'https://catalog.onliner.by/installations'),
        (226, 'Инструменты для ремонта и обслуживания велосипеда', null, 'https://catalog.onliner.by/bike_tools'),
        (227, 'Интерактивные игрушки и роботы', null, 'https://catalog.onliner.by/interactive_toys'),
        (228, 'Интерьерные часы', null, 'https://catalog.onliner.by/interior_clock'),
        (229, 'Информационные панели', null, 'https://catalog.onliner.by/digitalsignage'),
        (230, 'Источники бесперебойного питания', null, 'https://catalog.onliner.by/ups'),
        (231, 'Йогуртницы и мороженицы', null, 'https://catalog.onliner.by/yogurtmaker'),
        (232, 'Казаны', null, 'https://catalog.onliner.by/kazan'),
        (233, 'Камеры CCTV', null, 'https://catalog.onliner.by/cctvcamera'),
        (234, 'Карты оплаты и подписки', null, 'https://catalog.onliner.by/paymentcard'),
        (235, 'Кассовые аппараты', null, 'https://catalog.onliner.by/cashregister'),
        (236, 'Кастрюли', null, 'https://catalog.onliner.by/saucepan'),
        (237, 'Каталки, педальные машинки', null, 'https://catalog.onliner.by/rideon'),
        (238, 'Кашпо, горшки для растений', null, 'https://catalog.onliner.by/flowerpot'),
        (239, 'Квадроциклы', null, 'https://catalog.onliner.by/quad'),
        (240, 'Кемпинговая мебель', null, 'https://catalog.onliner.by/camp_furniture'),
        (241, 'Кирпич', null, 'https://catalog.onliner.by/bricks'),
        (242, 'Клавиши и системы смыва', null, 'https://catalog.onliner.by/flushing_system'),
        (243, 'Клеевые смеси', null, 'https://catalog.onliner.by/adhesivemix'),
        (244, 'Клеи и герметики для автомобилей', null, 'https://catalog.onliner.by/adhesivecar'),
        (245, 'Клетки и аксессуары для птиц и грызунов', null, 'https://catalog.onliner.by/pet_cage'),
        (246, 'Коврики для йоги и фитнеса', null, 'https://catalog.onliner.by/yoga_mat'),
        (247, 'Коляски', null, 'https://catalog.onliner.by/pram'),
        (248, 'Коммутаторы', null, 'https://catalog.onliner.by/switch'),
        (249, 'Комнатные растения, флорариумы', null, 'https://catalog.onliner.by/houseplant'),
        (250, 'Компрессоры', null, 'https://catalog.onliner.by/compressor'),
        (251, 'Кондиционеры', null, 'https://catalog.onliner.by/conditioners'),
        (252, 'Конструкторы', null, 'https://catalog.onliner.by/buildingkit'),
        (253, 'Контактные линзы', null, 'https://catalog.onliner.by/contact_lense'),
        (254, 'Концертная акустика', null, 'https://catalog.onliner.by/concertacoustics'),
        (255, 'Коньки', null, 'https://catalog.onliner.by/skates'),
        (256, 'Корма для кошек', null, 'https://catalog.onliner.by/catfood'),
        (257, 'Корма для собак', null, 'https://catalog.onliner.by/foodfordog'),
        (258, 'Косметические зеркала', null, 'https://catalog.onliner.by/cosmetic_mirror'),
        (259, 'Кофе', null, 'https://catalog.onliner.by/coffeejava'),
        (260, 'Кофемашины и кофеварки', null, 'https://catalog.onliner.by/coffee'),
        (261, 'Кофемолки', null, 'https://catalog.onliner.by/coffeegrinders'),
        (262, 'Кошельки', null, 'https://catalog.onliner.by/wallet'),
        (263, 'Краски и эмали', null, 'https://catalog.onliner.by/paints'),
        (264, 'Креатин', null, 'https://catalog.onliner.by/creatine'),
        (265, 'Кресла', null, 'https://catalog.onliner.by/interior_chair'),
        (266, 'Кровати', null, 'https://catalog.onliner.by/bed'),
        (267, 'Кровельные материалы', null, 'https://catalog.onliner.by/roof'),
        (268, 'Кронштейны', null, 'https://catalog.onliner.by/wallmount'),
        (269, 'Кружки, чашки, стаканы для горячих напитков', null, 'https://catalog.onliner.by/hot_drinks'),
        (270, 'Ксенон', null, 'https://catalog.onliner.by/xenon'),
        (271, 'Кукольные домики', null, 'https://catalog.onliner.by/dollhouses'),
        (272, 'Кулеры для воды', null, 'https://catalog.onliner.by/water_cooler'),
        (273, 'Кусторезы и высоторезы', null, 'https://catalog.onliner.by/hedgetrimmers'),
        (274, 'Кухонные весы', null, 'https://catalog.onliner.by/kitchenscales'),
        (275, 'Кухонные инструменты', null, 'https://catalog.onliner.by/kitchen_tools'),
        (276, 'Кухонные комбайны, машины и планетарные миксеры', null, 'https://catalog.onliner.by/foodprocessors'),
        (277, 'Кухонные мойки', null, 'https://catalog.onliner.by/kitchensink'),
        (278, 'Кухонные ножи, ножницы, овощечистки, точилки', null, 'https://catalog.onliner.by/kitchen_knife'),
        (279, 'Кухонные плиты', null, 'https://catalog.onliner.by/cooker'),
        (280, 'Кухонные столы и обеденные группы', null, 'https://catalog.onliner.by/kitchen_table'),
        (281, 'Лазерные дальномеры', null, 'https://catalog.onliner.by/laserdistmeter'),
        (282, 'Лазерные нивелиры', null, 'https://catalog.onliner.by/laserlevel'),
        (283, 'Лаки, пропитки, антисептики', null, 'https://catalog.onliner.by/lacquer'),
        (284, 'Ламинат', null, 'https://catalog.onliner.by/laminate'),
        (285, 'Ламинаторы', null, 'https://catalog.onliner.by/laminator'),
        (286, 'Лампочки', null, 'https://catalog.onliner.by/lightbulb'),
        (287, 'Лампы', null, 'https://catalog.onliner.by/autolamps'),
        (288, 'Ледобуры', null, 'https://catalog.onliner.by/icescrew'),
        (289, 'Лежанки, домики, когтеточки для кошек и собак', null, 'https://catalog.onliner.by/pet_house'),
        (290, 'Лекарственные травы и сборы', null, 'https://catalog.onliner.by/medicinal_plants'),
        (291, 'Лестницы и стремянки', null, 'https://catalog.onliner.by/stairandladder'),
        (292, 'Летние души', null, 'https://catalog.onliner.by/summer_shower'),
        (293, 'Линолеум', null, 'https://catalog.onliner.by/linoleum'),
        (294, 'Листовой металлопрокат', null, 'https://catalog.onliner.by/sheetmetal'),
        (295, 'Лобзики', null, 'https://catalog.onliner.by/fretsaw'),
        (296, 'Логические игры, головоломки', null, 'https://catalog.onliner.by/logic_puzzles'),
        (297, 'Лодочные моторы', null, 'https://catalog.onliner.by/outboardmotors'),
        (298, 'Ломтерезки', null, 'https://catalog.onliner.by/slicer'),
        (299, 'Лыжи', null, 'https://catalog.onliner.by/skis'),
        (300, 'Люстры и светильники', null, 'https://catalog.onliner.by/luster'),
        (301, 'Магнитолы', null, 'https://catalog.onliner.by/caraudio'),
        (302, 'Мангалы, грили, барбекю', null, 'https://catalog.onliner.by/grill'),
        (303, 'Манежи', null, 'https://catalog.onliner.by/playpen'),
        (304, 'Маникюрные и педикюрные наборы', null, 'https://catalog.onliner.by/manicure'),
        (305, 'Маринаторы', null, 'https://catalog.onliner.by/marinator'),
        (306, 'Мармиты, фондю', null, 'https://catalog.onliner.by/fondue'),
        (307, 'Масла для лодочных моторов', null, 'https://catalog.onliner.by/twostrokeoil'),
        (308, 'Массажеры и массажные кресла', null, 'https://catalog.onliner.by/massagechair'),
        (309, 'Матрасы', null, 'https://catalog.onliner.by/mattress'),
        (310, 'Матричные принтеры', null, 'https://catalog.onliner.by/matrixprinter'),
        (311, 'Машинки для стрижки волос', null, 'https://catalog.onliner.by/hairclipper'),
        (312, 'Машинки для удаления катышков', null, 'https://catalog.onliner.by/lintshaver'),
        (313, 'Мебель для ванных комнат', null, 'https://catalog.onliner.by/bath_furniture'),
        (314, 'Медиаплееры и ТВ-приставки', null, 'https://catalog.onliner.by/media'),
        (315, 'Медицинские маски, респираторы, защитные очки', null, 'https://catalog.onliner.by/medicalmask'),
        (316, 'Межкомнатные двери', null, 'https://catalog.onliner.by/interiordoor'),
        (317, 'Металлические двери', null, 'https://catalog.onliner.by/steeldoor'),
        (318, 'Металлообрабатывающие станки', null, 'https://catalog.onliner.by/metalworking'),
        (319, 'Метеостанции', null, 'https://catalog.onliner.by/meteostations'),
        (320, 'Микроволновые печи', null, 'https://catalog.onliner.by/microvawe'),
        (321, 'Микрофоны', null, 'https://catalog.onliner.by/microphones'),
        (322, 'Мини-печи', null, 'https://catalog.onliner.by/roaster'),
        (323, 'Мини-тракторы', null, 'https://catalog.onliner.by/minitractor'),
        (324, 'Миски, дуршлаги, сита', null, 'https://catalog.onliner.by/bowls'),
        (325, 'Миски, поилки, кормушки для животных', null, 'https://catalog.onliner.by/animal_plate'),
        (326, 'Мойки высокого давления', null, 'https://catalog.onliner.by/washers'),
        (327, 'Молокоотсосы и аксессуары', null, 'https://catalog.onliner.by/breast_pump'),
        (328, 'Мотоблоки и мотокультиваторы', null, 'https://catalog.onliner.by/motoblock'),
        (329, 'Мотопомпы', null, 'https://catalog.onliner.by/motopump'),
        (330, 'Моторные масла', null, 'https://catalog.onliner.by/motor_oil'),
        (331, 'Мотоциклетные аккумуляторы', null, 'https://catalog.onliner.by/motobatteries'),
        (332, 'Мотоциклетные шины', null, 'https://catalog.onliner.by/moto_tires'),
        (333, 'Мотоциклы', null, 'https://catalog.onliner.by/motorcycle'),
        (334, 'Мотошлемы', null, 'https://catalog.onliner.by/motohelmet'),
        (335, 'Мужские электробритвы', null, 'https://catalog.onliner.by/shaver'),
        (336, 'Мультиварки', null, 'https://catalog.onliner.by/multicooker'),
        (337, 'Мультиметры, токовые клещи, индикаторные отвертки', null, 'https://catalog.onliner.by/multimeter'),
        (338, 'Мусорки, урны, контейнеры для мусора', null, 'https://catalog.onliner.by/trashbin'),
        (339, 'Мягкие игрушки', null, 'https://catalog.onliner.by/stuffedtoys'),
        (340, 'Мясорубки', null, 'https://catalog.onliner.by/meatgrinder'),
        (341, 'Мячи', null, 'https://catalog.onliner.by/ball'),
        (342, 'Наборы инструментов', null, 'https://catalog.onliner.by/tool_kits'),
        (343, 'Навесное оборудование для садовой техники', null, 'https://catalog.onliner.by/attachmentgarden'),
        (344, 'Надувная мебель', null, 'https://catalog.onliner.by/airbed'),
        (345, 'Надувные лодки', null, 'https://catalog.onliner.by/inflatableboat'),
        (346, 'Наматрасники', null, 'https://catalog.onliner.by/mattresspad'),
        (347, 'Напольные весы', null, 'https://catalog.onliner.by/scales'),
        (348, 'Наручные часы', null, 'https://catalog.onliner.by/watch'),
        (349, 'Насосы', null, 'https://catalog.onliner.by/pump'),
        (350, 'Настольные игры', null, 'https://catalog.onliner.by/boardgame'),
        (351, 'Настольные плиты', null, 'https://catalog.onliner.by/tabletop_cooker'),
        (352, 'Наушники', null, 'https://catalog.onliner.by/headphones'),
        (353, 'Нитратомеры, дозиметры, экотестеры', null, 'https://catalog.onliner.by/nitrate'),
        (354, 'Обезболивающие препараты', null, 'https://catalog.onliner.by/painkillers'),
        (355, 'Обложки для электронных книг', null, 'https://catalog.onliner.by/ebookcover'),
        (356, 'Обогреватели', null, 'https://catalog.onliner.by/heater'),
        (357, 'Общестроительные материалы', null, 'https://catalog.onliner.by/buildingmaterial'),
        (358, 'Объективы', null, 'https://catalog.onliner.by/lens'),
        (359, 'Оверлоки', null, 'https://catalog.onliner.by/overlock'),
        (360, 'Огнетушители', null, 'https://catalog.onliner.by/extinguisher'),
        (361, 'Одежда для охоты, рыбалки', null, 'https://catalog.onliner.by/hunter_clothes'),
        (362, 'Окна ПВХ', null, 'https://catalog.onliner.by/vynilwindows'),
        (363, 'Опрыскиватели', null, 'https://catalog.onliner.by/sprayer'),
        (364, 'Органайзеры и системы хранения инструментов', null, 'https://catalog.onliner.by/toolbox'),
        (365, 'Ортопедические подушки', null, 'https://catalog.onliner.by/pillow'),
        (366, 'Основания для кроватей', null, 'https://catalog.onliner.by/orthobase'),
        (367, 'Осушители воздуха', null, 'https://catalog.onliner.by/dehumidifier'),
        (368, 'Отбойные молотки', null, 'https://catalog.onliner.by/jackhammer'),
        (369, 'Отопительные котлы', null, 'https://catalog.onliner.by/boiler'),
        (370, 'Офисные доски, флипчарты', null, 'https://catalog.onliner.by/officeboard'),
        (371, 'Офисные кресла, стулья', null, 'https://catalog.onliner.by/office_chair'),
        (372, 'Охлаждающие жидкости', null, 'https://catalog.onliner.by/antifreeze'),
        (373, 'Охлаждающие подставки', null, 'https://catalog.onliner.by/laptopstand'),
        (374, 'Очистители и мойки воздуха', null, 'https://catalog.onliner.by/airpurifier'),
        (375, 'Очки виртуальной реальности', null, 'https://catalog.onliner.by/virtualreality'),
        (376, 'Палатки', null, 'https://catalog.onliner.by/tents'),
        (377, 'Палки для селфи', null, 'https://catalog.onliner.by/selfiestick'),
        (378, 'Радионяни и видеоняни', null, 'https://catalog.onliner.by/babymonitor'),
        (379, 'Палки для скандинавской ходьбы', null, 'https://catalog.onliner.by/nordic_walking'),
        (380, 'Паркетная доска', null, 'https://catalog.onliner.by/parquetboard'),
        (381, 'Парковочные радары и камеры заднего вида', null, 'https://catalog.onliner.by/parkingradar'),
        (382, 'Пароварки', null, 'https://catalog.onliner.by/steamers'),
        (383, 'Пароварки, мантоварки', null, 'https://catalog.onliner.by/steamer'),
        (384, 'Парфюмерия', null, 'https://catalog.onliner.by/parfume'),
        (385, 'Паяльники и паяльные лампы', null, 'https://catalog.onliner.by/solderingiron'),
        (386, 'Перфораторы', null, 'https://catalog.onliner.by/rotaryhammers'),
        (387, 'Перчатки для бокса и единоборств', null, 'https://catalog.onliner.by/glovesmartialart'),
        (388, 'Письменные и компьютерные столы', null, 'https://catalog.onliner.by/table'),
        (389, 'Пледы, покрывала', null, 'https://catalog.onliner.by/plaid'),
        (390, 'Плиткорезы', null, 'https://catalog.onliner.by/tilecutter'),
        (391, 'Плойки, стайлеры, щипцы', null, 'https://catalog.onliner.by/styler'),
        (392, 'Пневматические гайковерты', null, 'https://catalog.onliner.by/wrench'),
        (393, 'Пневматические краскопульты', null, 'https://catalog.onliner.by/spraygun'),
        (394, 'Пневмошлифмашины', null, 'https://catalog.onliner.by/pneumogrinder'),
        (395, 'Подгузники', null, 'https://catalog.onliner.by/diapers'),
        (396, 'Подогреватели и стерилизаторы бутылочек', null, 'https://catalog.onliner.by/bottlesterilizer'),
        (397, 'Подъемники', null, 'https://catalog.onliner.by/carlift'),
        (398, 'Поливочные шланги', null, 'https://catalog.onliner.by/garden_hose'),
        (399, 'Поликарбонат для теплиц', null, 'https://catalog.onliner.by/polycarbonate'),
        (400, 'Полотенцесушители', null, 'https://catalog.onliner.by/towelrail'),
        (401, 'Портативные радиостанции', null, 'https://catalog.onliner.by/portableradio'),
        (402, 'Постельное белье', null, 'https://catalog.onliner.by/bedlinen'),
        (403, 'Посуда для хранения продуктов', null, 'https://catalog.onliner.by/food_storage'),
        (404, 'Посудомоечные машины', null, 'https://catalog.onliner.by/dishwasher'),
        (405, 'Предметы сервировки', null, 'https://catalog.onliner.by/serving'),
        (406, 'Предпусковые подогреватели двигателя и топливной системы', null, 'https://catalog.onliner.by/dieselfuelheater'),
        (407, 'Препараты для коррекции и лечения астмы', null, 'https://catalog.onliner.by/asthma_med'),
        (408, 'Препараты для лечения заболеваний глаз и ушей', null, 'https://catalog.onliner.by/eyes_ears_med'),
        (409, 'Препараты для лечения заболеваний ЖКТ', null, 'https://catalog.onliner.by/gitract_med'),
        (410, 'Препараты для лечения заболеваний зубов и полости рта', null, 'https://catalog.onliner.by/teeth_med'),
        (411, 'Препараты для лечения заболеваний кожи', null, 'https://catalog.onliner.by/skin_med'),
        (412, 'Препараты для лечения заболеваний мочеполового тракта', null, 'https://catalog.onliner.by/urogenital_med'),
        (413, 'Препараты для лечения заболеваний нервной системы', null, 'https://catalog.onliner.by/nervous_system'),
        (414, 'Препараты для лечения заболеваний сердечно-сосудистой системы', null, 'https://catalog.onliner.by/cardio_med'),
        (415, 'Препараты для лечения от алкогольной и никотиновой зависимости', null, 'https://catalog.onliner.by/alcoholism_med'),
        (416, 'Приборы для ухода за кожей', null, 'https://catalog.onliner.by/skin_care_app'),
        (417, 'Приборы для физиотерапии', null, 'https://catalog.onliner.by/physical_therapy'),
        (418, 'Приемники цифрового ТВ', null, 'https://catalog.onliner.by/terrestrial'),
        (419, 'Принадлежности для барбекю, грилей, мангалов', null, 'https://catalog.onliner.by/bbq_accessories'),
        (420, 'Принтеры на этикетках и чеках', null, 'https://catalog.onliner.by/thermal'),
        (421, 'Присадки для авто', null, 'https://catalog.onliner.by/additive4fuel'),
        (422, 'Приточные и вытяжные вентиляторы', null, 'https://catalog.onliner.by/exhaustfan'),
        (423, 'Проводные телефоны', null, 'https://catalog.onliner.by/phone'),
        (424, 'Проекторы', null, 'https://catalog.onliner.by/projectors'),
        (425, 'Проекционные экраны', null, 'https://catalog.onliner.by/projectorscreen'),
        (426, 'Промышленные фены', null, 'https://catalog.onliner.by/industrialdryer'),
        (427, 'Протеин', null, 'https://catalog.onliner.by/protein'),
        (428, 'Противовирусные и противопростудные препараты', null, 'https://catalog.onliner.by/antiviral_med'),
        (429, 'Противогрибковые препараты', null, 'https://catalog.onliner.by/tineaunguium_med'),
        (430, 'Пульсометры, пульсоксиметры', null, 'https://catalog.onliner.by/heart_rate'),
        (431, 'Пускозарядные устройства', null, 'https://catalog.onliner.by/start_charge'),
        (432, 'Пуфы', null, 'https://catalog.onliner.by/puffs'),
        (433, 'Пылесосы', null, 'https://catalog.onliner.by/vacuumcleaner'),
        (434, 'Пьедесталы для умывальников', null, 'https://catalog.onliner.by/pedestal'),
        (435, 'Радар-детекторы', null, 'https://catalog.onliner.by/radar'),
        (436, 'Радиаторы отопления', null, 'https://catalog.onliner.by/radiators'),
        (437, 'Радиоприемники', null, 'https://catalog.onliner.by/radio'),
        (438, 'Радиостанции CB', null, 'https://catalog.onliner.by/car_radio'),
        (439, 'Радиотелефоны DECT', null, 'https://catalog.onliner.by/dect'),
        (440, 'Радиоуправляемые авиамодели', null, 'https://catalog.onliner.by/radiocontrolair'),
        (441, 'Радиоуправляемые автомодели', null, 'https://catalog.onliner.by/radioautomodel'),
        (442, 'Радиоуправляемые судомодели', null, 'https://catalog.onliner.by/radiomodelwater'),
        (443, 'Развивающие игрушки', null, 'https://catalog.onliner.by/edu_toys'),
        (444, 'Развивающие коврики', null, 'https://catalog.onliner.by/playmats'),
        (445, 'Разделочные доски', null, 'https://catalog.onliner.by/cutting_boards'),
        (446, 'Ракетки, мячи и аксессуары для настольного тенниса', null, 'https://catalog.onliner.by/racktabletennis'),
        (447, 'Растворы для инфузий, местные анестетики', null, 'https://catalog.onliner.by/anesthesia'),
        (448, 'Растворы для линз', null, 'https://catalog.onliner.by/solutionlenses'),
        (449, 'Расходные материалы для 3D-печати', null, 'https://catalog.onliner.by/3d_filament'),
        (450, 'Резаки для бумаги', null, 'https://catalog.onliner.by/papercutter'),
        (451, 'Роботы, трансформеры, фигурки', null, 'https://catalog.onliner.by/robots'),
        (452, 'Розетки, выключатели', null, 'https://catalog.onliner.by/wall_socket'),
        (453, 'Роликовые коньки', null, 'https://catalog.onliner.by/rollerskates'),
        (454, 'Рубанки', null, 'https://catalog.onliner.by/plane'),
        (455, 'Ручные миксеры', null, 'https://catalog.onliner.by/mixer'),
        (456, 'Ручные соковыжималки', null, 'https://catalog.onliner.by/handjuicer'),
        (457, 'Рыболовные катушки', null, 'https://catalog.onliner.by/coil'),
        (458, 'Рюкзаки', null, 'https://catalog.onliner.by/backpack'),
        (459, 'Рюкзаки-переноски (кенгуру)', null, 'https://catalog.onliner.by/babycarrier'),
        (460, 'Садовая мебель', null, 'https://catalog.onliner.by/gardenfurniture'),
        (461, 'Садовые измельчители', null, 'https://catalog.onliner.by/gardenshredder'),
        (462, 'Садовые качели', null, 'https://catalog.onliner.by/gardenswing'),
        (463, 'Садовый инструмент', null, 'https://catalog.onliner.by/gardentool'),
        (464, 'Самокаты', null, 'https://catalog.onliner.by/kickscooter'),
        (465, 'Санки', null, 'https://catalog.onliner.by/sled'),
        (466, 'Сантехнические ревизионные люки', null, 'https://catalog.onliner.by/access_panel'),
        (467, 'Саундбары и домашние кинотеатры', null, 'https://catalog.onliner.by/soundbar'),
        (468, 'Сборные модели', null, 'https://catalog.onliner.by/scale_model'),
        (469, 'Сварочные аппараты', null, 'https://catalog.onliner.by/weldinginverter'),
        (470, 'Сварочные маски', null, 'https://catalog.onliner.by/weldingmask'),
        (471, 'Светофильтры и конвертеры', null, 'https://catalog.onliner.by/photofilter'),
        (472, 'Сейфы', null, 'https://catalog.onliner.by/furnituresafes'),
        (473, 'Семена овощей, зелени и ягод', null, 'https://catalog.onliner.by/vegetableseed'),
        (474, 'Семена трав, газон', null, 'https://catalog.onliner.by/lawn'),
        (475, 'Сетевые проигрыватели', null, 'https://catalog.onliner.by/network_player'),
        (476, 'Сети по электропроводке (Powerline)', null, 'https://catalog.onliner.by/powerline'),
        (546, 'Триммеры', null, 'https://catalog.onliner.by/trimmers'),
        (477, 'Силовые тренажеры', null, 'https://catalog.onliner.by/strengthtrain'),
        (478, 'Синтезаторы и рабочие станции', null, 'https://catalog.onliner.by/synthandworkst'),
        (479, 'Системы автоматического полива, распылители', null, 'https://catalog.onliner.by/watering_system'),
        (480, 'Сифоны', null, 'https://catalog.onliner.by/siphon'),
        (481, 'Сканеры штрих-кодов', null, 'https://catalog.onliner.by/barcode'),
        (482, 'Скейтборды', null, 'https://catalog.onliner.by/skateboard'),
        (483, 'Скобозабиватели, гвоздезабиватели, степлеры', null, 'https://catalog.onliner.by/nailer'),
        (484, 'Сковороды', null, 'https://catalog.onliner.by/pan'),
        (485, 'Скороварки', null, 'https://catalog.onliner.by/pressure_cooker'),
        (486, 'Скутеры и мопеды', null, 'https://catalog.onliner.by/scooter'),
        (487, 'Смазки, пасты и очистители для механических, электрических узлов', null, 'https://catalog.onliner.by/grease'),
        (488, 'Сменные ремешки и браслеты', null, 'https://catalog.onliner.by/replacementstrap'),
        (489, 'Смеси для полов', null, 'https://catalog.onliner.by/floormix'),
        (490, 'Смесители', null, 'https://catalog.onliner.by/faucet'),
        (491, 'Снегоуборщики', null, 'https://catalog.onliner.by/snowblower'),
        (492, 'Соковыжималки', null, 'https://catalog.onliner.by/juicer'),
        (493, 'Спальные мешки', null, 'https://catalog.onliner.by/sleepingbag'),
        (494, 'Спортивная защита', null, 'https://catalog.onliner.by/sportsprotection'),
        (495, 'Спутниковые ресиверы', null, 'https://catalog.onliner.by/satellite'),
        (496, 'Средства для биотуалетов, выгребных ям', null, 'https://catalog.onliner.by/wc_liquid'),
        (497, 'Средства для окрашивания волос', null, 'https://catalog.onliner.by/hair_color'),
        (498, 'Средства для посудомоечных машин', null, 'https://catalog.onliner.by/dishwashertablet'),
        (499, 'Средства для стирки и ухода за бельем', null, 'https://catalog.onliner.by/washingpowder'),
        (500, 'Средства для укладки волос', null, 'https://catalog.onliner.by/hair_styling'),
        (501, 'Средства по уходу за ногтями', null, 'https://catalog.onliner.by/nailcare'),
        (502, 'Стабилизаторы и сетевые фильтры', null, 'https://catalog.onliner.by/voltageregulator'),
        (503, 'Стаканы, бокалы, рюмки', null, 'https://catalog.onliner.by/glassware'),
        (504, 'Стеклоомывающие жидкости', null, 'https://catalog.onliner.by/washerfluid'),
        (505, 'Стеновые панели', null, 'https://catalog.onliner.by/wall_panels'),
        (506, 'Степперы', null, 'https://catalog.onliner.by/stepper'),
        (507, 'Стиральные машины', null, 'https://catalog.onliner.by/washingmachine'),
        (508, 'Столовые приборы', null, 'https://catalog.onliner.by/cutlery'),
        (509, 'Строительные и садовые тачки', null, 'https://catalog.onliner.by/barrow'),
        (510, 'Строительные сетки', null, 'https://catalog.onliner.by/rabitz'),
        (511, 'Строительный, слесарный, монтажный инструмент', null, 'https://catalog.onliner.by/household_tools'),
        (512, 'Студийные мониторы', null, 'https://catalog.onliner.by/studio_monitor'),
        (513, 'Стульчики для кормления', null, 'https://catalog.onliner.by/highchair'),
        (514, 'Стулья для кухни и бара', null, 'https://catalog.onliner.by/chair'),
        (515, 'Сумки для ноутбуков', null, 'https://catalog.onliner.by/notebookcase'),
        (516, 'Сумки и рюкзаки для фото/видео', null, 'https://catalog.onliner.by/case'),
        (517, 'Сумки, переноски для животных', null, 'https://catalog.onliner.by/pet_carrier'),
        (518, 'Сушилки для белья', null, 'https://catalog.onliner.by/linendryer'),
        (519, 'Сушилки для овощей и фруктов', null, 'https://catalog.onliner.by/food_dehydrator'),
        (520, 'Сушилки для рук, волос', null, 'https://catalog.onliner.by/handsdryer'),
        (521, 'Счетчики банкнот и монет', null, 'https://catalog.onliner.by/counters'),
        (522, 'Счетчики воды', null, 'https://catalog.onliner.by/water_meter'),
        (523, 'Счетчики газа', null, 'https://catalog.onliner.by/gas_meter'),
        (524, 'Счетчики электроэнергии', null, 'https://catalog.onliner.by/electro_meter'),
        (525, 'Сэндвичницы', null, 'https://catalog.onliner.by/sandwichers'),
        (526, 'Тарелки, салатники, блюда и наборы', null, 'https://catalog.onliner.by/dishset'),
        (527, 'ТВ-антенны', null, 'https://catalog.onliner.by/aerial'),
        (528, 'Телевизоры', null, 'https://catalog.onliner.by/tv'),
        (529, 'Телескопы', null, 'https://catalog.onliner.by/telescope'),
        (530, 'Теннисные столы', null, 'https://catalog.onliner.by/tabletennis'),
        (531, 'Теплицы и парники', null, 'https://catalog.onliner.by/greenhouse'),
        (532, 'Тепловые завесы', null, 'https://catalog.onliner.by/aircurtain'),
        (533, 'Тепловые пушки', null, 'https://catalog.onliner.by/heat_gun'),
        (534, 'Теплоизоляция', null, 'https://catalog.onliner.by/therminsulation'),
        (535, 'Теплые полы', null, 'https://catalog.onliner.by/heatedfloor'),
        (536, 'Терки, измельчители, овощерезки', null, 'https://catalog.onliner.by/grater'),
        (537, 'Термоклеевые пистолеты', null, 'https://catalog.onliner.by/hotgluegun'),
        (538, 'Термометры', null, 'https://catalog.onliner.by/medthermometer'),
        (539, 'Терморегуляторы', null, 'https://catalog.onliner.by/thermostat'),
        (540, 'Термосы, термокружки', null, 'https://catalog.onliner.by/thermosbottle'),
        (541, 'Тонометры', null, 'https://catalog.onliner.by/tonometers'),
        (542, 'Торговые холодильники', null, 'https://catalog.onliner.by/commfrige'),
        (543, 'Тормозные жидкости', null, 'https://catalog.onliner.by/brakefluid'),
        (544, 'Тостеры', null, 'https://catalog.onliner.by/toaster'),
        (545, 'Трансмиссионные масла', null, 'https://catalog.onliner.by/gearoil'),
        (547, 'Тротуарная плитка', null, 'https://catalog.onliner.by/pavers'),
        (548, 'Трубный металлопрокат', null, 'https://catalog.onliner.by/metal_pipes'),
        (549, 'Трубы, фитинг', null, 'https://catalog.onliner.by/tube_fitting'),
        (550, 'Туалетные столики', null, 'https://catalog.onliner.by/dressing_table'),
        (551, 'Тумбы для обуви', null, 'https://catalog.onliner.by/shoe_cabinets'),
        (552, 'Тумбы под телевизор', null, 'https://catalog.onliner.by/tv_stands'),
        (553, 'Туристические горелки и плиты', null, 'https://catalog.onliner.by/gascylinder'),
        (554, 'Туристические коврики', null, 'https://catalog.onliner.by/travel_mat'),
        (555, 'Туристические навигаторы', null, 'https://catalog.onliner.by/travelgps'),
        (556, 'Туристические ножи', null, 'https://catalog.onliner.by/foldingknives'),
        (557, 'Увлажнители воздуха', null, 'https://catalog.onliner.by/humidifier'),
        (558, 'Угловые шлифмашины (болгарки)', null, 'https://catalog.onliner.by/angle_grinder'),
        (559, 'Удобрения', null, 'https://catalog.onliner.by/fertilizer'),
        (560, 'Удочки, спиннинги', null, 'https://catalog.onliner.by/rod'),
        (561, 'Укрывной материал', null, 'https://catalog.onliner.by/coveringmaterial'),
        (562, 'Умный дом', null, 'https://catalog.onliner.by/smart_home'),
        (563, 'Умывальники', null, 'https://catalog.onliner.by/washbasin'),
        (564, 'Универсальные пульты ДУ', null, 'https://catalog.onliner.by/remote'),
        (565, 'Унитазы', null, 'https://catalog.onliner.by/wcpan'),
        (566, 'Уничтожители бумаг (шредеры)', null, 'https://catalog.onliner.by/shredder'),
        (567, 'Уничтожители насекомых', null, 'https://catalog.onliner.by/insect_killer'),
        (568, 'Усилители', null, 'https://catalog.onliner.by/caramps'),
        (569, 'Устройства для приготовления детского питания', null, 'https://catalog.onliner.by/babyfoodmaker'),
        (570, 'Утюги', null, 'https://catalog.onliner.by/iron'),
        (571, 'Утятницы, тажины', null, 'https://catalog.onliner.by/stewingdish'),
        (572, 'Уход за волосами', null, 'https://catalog.onliner.by/haircare'),
        (573, 'Уход за лицом', null, 'https://catalog.onliner.by/facial_cosmetics'),
        (574, 'Уход за телом', null, 'https://catalog.onliner.by/body_care'),
        (575, 'Факсы', null, 'https://catalog.onliner.by/fax'),
        (576, 'Фены', null, 'https://catalog.onliner.by/hairdryer'),
        (577, 'Фиджет спиннеры', null, 'https://catalog.onliner.by/fidget_spinner'),
        (578, 'Фильтры и системы очистки воды', null, 'https://catalog.onliner.by/waterfilter'),
        (579, 'Фонари', null, 'https://catalog.onliner.by/lights'),
        (580, 'Фонокорректоры', null, 'https://catalog.onliner.by/phonopreamps'),
        (581, 'Формы для выпечки, противни', null, 'https://catalog.onliner.by/breadpan'),
        (582, 'Фотоаппараты', null, 'https://catalog.onliner.by/photo'),
        (583, 'Фотоловушки', null, 'https://catalog.onliner.by/camera_traps'),
        (584, 'Фрезеры', null, 'https://catalog.onliner.by/woodrouter'),
        (585, 'Фритюрницы', null, 'https://catalog.onliner.by/fryer'),
        (586, 'Хлебопечки', null, 'https://catalog.onliner.by/breadmaker'),
        (587, 'Ходунки, прыгунки', null, 'https://catalog.onliner.by/babywalker'),
        (588, 'Хоккейные клюшки', null, 'https://catalog.onliner.by/hockeystick'),
        (589, 'Холодильники', null, 'https://catalog.onliner.by/refrigerator'),
        (590, 'Хондропротекторы', null, 'https://catalog.onliner.by/chondroprotect'),
        (591, 'Цветы, букеты', null, 'https://catalog.onliner.by/flowersbouquets'),
        (592, 'Цемент', null, 'https://catalog.onliner.by/caementum'),
        (593, 'Цепные пилы', null, 'https://catalog.onliner.by/chainsaw'),
        (594, 'Цифровые фоторамки', null, 'https://catalog.onliner.by/photoframe'),
        (595, 'Чайники', null, 'https://catalog.onliner.by/kettles'),
        (596, 'Чемоданы и дорожные сумки', null, 'https://catalog.onliner.by/suitcase'),
        (597, 'Чехлы для планшетов', null, 'https://catalog.onliner.by/tabletcase'),
        (598, 'Чехлы для телефонов', null, 'https://catalog.onliner.by/phonecase'),
        (599, 'Чугунки, горшочки', null, 'https://catalog.onliner.by/pots'),
        (600, 'Шатры, тенты', null, 'https://catalog.onliner.by/canopy_tents'),
        (601, 'Шахматы, шашки, нарды', null, 'https://catalog.onliner.by/chess'),
        (602, 'Швейные машины', null, 'https://catalog.onliner.by/sewingmachines'),
        (603, 'Шезлонги', null, 'https://catalog.onliner.by/lounger'),
        (604, 'Шлифмашины', null, 'https://catalog.onliner.by/grinder'),
        (605, 'Шпатлевка', null, 'https://catalog.onliner.by/putty'),
        (606, 'Штативы', null, 'https://catalog.onliner.by/tripod'),
        (607, 'Штроборезы', null, 'https://catalog.onliner.by/wallchaser'),
        (608, 'Штукатурка', null, 'https://catalog.onliner.by/plaster'),
        (609, 'Экраны под ванну', null, 'https://catalog.onliner.by/bath_panels'),
        (610, 'Экшен-камеры', null, 'https://catalog.onliner.by/actioncamera'),
        (611, 'Электрические гирлянды', null, 'https://catalog.onliner.by/xmaslights'),
        (612, 'Электрические зарядные станции', null, 'https://catalog.onliner.by/charging_station'),
        (613, 'Электрические краскораспылители', null, 'https://catalog.onliner.by/electricspraygun'),
        (614, 'Электрические ножницы по металлу', null, 'https://catalog.onliner.by/metal_cutter'),
        (615, 'Электрические сушилки для обуви', null, 'https://catalog.onliner.by/shoes_dryer'),
        (616, 'Электро- и бензорезы', null, 'https://catalog.onliner.by/powercutter'),
        (617, 'Электровелосипеды', null, 'https://catalog.onliner.by/electrobike'),
        (618, 'Электровеники', null, 'https://catalog.onliner.by/sweeper'),
        (619, 'Электрогрелки, электроодеяла, электропростыни', null, 'https://catalog.onliner.by/mobile_heater'),
        (620, 'Электрогрили', null, 'https://catalog.onliner.by/electricgrill'),
        (621, 'Электродрели и строительные миксеры', null, 'https://catalog.onliner.by/drills'),
        (622, 'Электрокамины и биокамины', null, 'https://catalog.onliner.by/electrofireplace'),
        (623, 'Электромобили', null, 'https://catalog.onliner.by/electricrideon'),
        (624, 'Электронные и радиочасы', null, 'https://catalog.onliner.by/clockradio'),
        (625, 'Электронные книги', null, 'https://catalog.onliner.by/ebook'),
        (626, 'Электронные крышки-биде', null, 'https://catalog.onliner.by/toilet_shower'),
        (627, 'Электронные парогенераторы', null, 'https://catalog.onliner.by/smoke'),
        (628, 'Электросамокаты и электроскутеры', null, 'https://catalog.onliner.by/electric_scooter'),
        (629, 'Электрочайники и термопоты', null, 'https://catalog.onliner.by/kettle'),
        (630, 'Электрошашлычницы', null, 'https://catalog.onliner.by/electrobarbecue'),
        (631, 'Электрошвабры, паровые швабры и полотеры', null, 'https://catalog.onliner.by/electric_mop'),
        (632, 'Эллиптические тренажеры', null, 'https://catalog.onliner.by/ellipsoids'),
        (633, 'Эхолоты', null, 'https://catalog.onliner.by/sounder'),
        (634, 'Яйцеварки', null, 'https://catalog.onliner.by/eggmaker'),
        (635, 'Ящики, корзины, органайзеры', null, 'https://catalog.onliner.by/toystorage'),
        (636, 'Кабели, адаптеры, разветвители', null, 'https://catalog.onliner.by/cable'),
        (637, 'Зарядные устройства', null, 'https://catalog.onliner.by/chargersmobile'),
        (638, 'AV-ресиверы и усилители', null, 'https://catalog.onliner.by/recievers'),
        (639, 'Музыкальные центры, колонки для вечеринок', null, 'https://catalog.onliner.by/hifiaudio'),
        (640, 'Плееры', null, 'https://catalog.onliner.by/player'),
        (641, 'Видеонаблюдение', null, 'https://catalog.onliner.by/dvr'),
        (642, 'Пароочистители и отпариватели', null, 'https://catalog.onliner.by/steamcleaner'),
        (643, 'Беспроводные адаптеры', null, 'https://catalog.onliner.by/wirelessadapter'),
        (644, 'Беспроводные точки доступа и усилители Wi-Fi', null, 'https://catalog.onliner.by/wirelessap'),
        (645, 'Шуруповерты, гайковерты, электроотвертки', null, 'https://catalog.onliner.by/screwdriver'),
        (646, 'Электропилы', null, 'https://catalog.onliner.by/electric_saw'),
        (647, 'Подарочные наборы', null, 'https://catalog.onliner.by/giftbox');