insert into public.countries (id, name_ru, name_en, iso3166alpha2, iso3166alpha3, iso3166numeric, continent)
values  (1, 'Андорра', 'Andorra', 'AD ', 'AND ', '20 ', 3),
        (9, 'Ангола', 'Angola', 'AO ', 'AGO ', '24 ', 1),
        (10, 'Антарктика', 'Antarctica', 'AQ ', 'ATA ', '10 ', 7),
        (4, 'Антигуа и Барбуда', 'Antigua and Barbuda', 'AG ', 'ATG ', '28 ', 4),
        (11, 'Аргентина', 'Argentina', 'AR ', 'ARG ', '32 ', 6),
        (7, 'Армения', 'Armenia', 'AM ', 'ARM ', '51 ', 2),
        (15, 'Аруба', 'Aruba', 'AW ', 'ABW ', '533', 4),
        (13, 'Австрия', 'Austria', 'AT ', 'AUT ', '40 ', 3),
        (16, 'Азербайджан', 'Azerbaijan', 'AZ ', 'AZE ', '31 ', 2),
        (31, 'Багамы', 'Bahamas', 'BS ', 'BHS ', '44 ', 4),
        (23, 'Бахрейн', 'Bahrain', 'BH ', 'BHR ', '48 ', 2),
        (18, 'Барбадос', 'Barbados', 'BB ', 'BRB ', '52 ', 4),
        (35, 'Беларусь', 'Belarus', 'BY ', 'BLR ', '112', 3),
        (20, 'Бельгия', 'Belgium', 'BE ', 'BEL ', '56 ', 3),
        (36, 'Белиз', 'Belize', 'BZ ', 'BLZ ', '84 ', 4),
        (25, 'Бенин', 'Benin', 'BJ ', 'BEN ', '204', 1),
        (27, 'Бермуды', 'Bermuda', 'BM ', 'BMU ', '60 ', 4),
        (32, 'Бутан', 'Bhutan', 'BT ', 'BTN ', '64 ', 2),
        (17, 'Босния и Герцеговина', 'Bosnia and Herzegovina', 'BA ', 'BIH ', '70 ', 3),
        (34, 'Ботсвана', 'Botswana', 'BW ', 'BWA ', '72 ', 1),
        (30, 'Бразилия', 'Brazil', 'BR ', 'BRA ', '76 ', 6),
        (28, 'Бруней', 'Brunei Darussalam', 'BN ', 'BRN ', '96 ', 2),
        (22, 'Болгария', 'Bulgaria', 'BG ', 'BGR ', '100', 3),
        (21, 'Буркина-Фасо', 'Burkina Faso', 'BF ', 'BFA ', '854', 1),
        (24, 'Бурунди', 'Burundi', 'BI ', 'BDI ', '108', 1),
        (49, 'Кабо-Верде', 'Cabo Verde', 'CV ', 'CPV ', '132', 1),
        (37, 'Канада', 'Canada', 'CA ', 'CAN ', '124', 4),
        (40, 'Центральноафриканская Республика', 'Central African Republic', 'CF ', 'CAF ', '140', 1),
        (44, 'Китай', 'China', 'CN ', 'CHN ', '156', 2),
        (51, 'Остров Рождества', 'Christmas Island', 'CX ', 'CXR ', '162', 5),
        (38, 'Кокосовые острова', 'Cocos (Keeling) Islands', 'CC ', 'CCK ', '166', 2),
        (45, 'Колумбия', 'Colombia', 'CO ', 'COL ', '170', 6),
        (41, 'Конго', 'Congo', 'CG ', 'COG ', '178', 1),
        (46, 'Коста-Рика', 'Costa Rica', 'CR ', 'CRI ', '188', 4),
        (43, 'Кот-д''Ивуар', 'Côte d''Ivoire', 'CI ', 'CIV ', '384', 1),
        (95, 'Хорватия', 'Croatia', 'HR ', 'HRV ', '191', 3),
        (48, 'Куба', 'Cuba', 'CU ', 'CUB ', '192', 4),
        (50, 'Кюрасао', 'Curaçao', 'CW ', 'CUW ', '531', 4),
        (52, 'Кипр', 'Cyprus', 'CY ', 'CYP ', '196', 3),
        (56, 'Дания', 'Denmark', 'DK ', 'DNK ', '208', 3),
        (55, 'Джибути', 'Djibouti', 'DJ ', 'DJI ', '262', 1),
        (57, 'Доминика', 'Dominica', 'DM ', 'DMA ', '212', 4),
        (60, 'Экадор', 'Ecuador', 'EC ', 'ECU ', '218', 6),
        (62, 'Египет', 'Egypt', 'EG ', 'EGY ', '818', 1),
        (85, 'Экваториальная Гвинея', 'Equatorial Guinea', 'GQ ', 'GNQ ', '226', 1),
        (64, 'Эритрея', 'Eritrea', 'ER ', 'ERI ', '232', 1),
        (61, 'Эстония', 'Estonia', 'EE ', 'EST ', '233', 3),
        (66, 'Эфиопия', 'Ethiopia', 'ET ', 'ETH ', '231', 1),
        (71, 'Фарерские о-ва', 'Faroe Islands', 'FO ', 'FRO ', '234', 3),
        (68, 'Фиджи', 'Fiji', 'FJ ', 'FJI ', '242', 5),
        (67, 'Финляндия', 'Finland', 'FI ', 'FIN ', '246', 3),
        (72, 'Франция', 'France', 'FR ', 'FRA ', '250', 3),
        (77, 'Французская Гвиана', 'French Guiana', 'GF ', 'GUF ', '254', 6),
        (73, 'Габон', 'Gabon', 'GA ', 'GAB ', '266', 1),
        (82, 'Гамбия', 'Gambia', 'GM ', 'GMB ', '270', 1),
        (76, 'Грузия', 'Georgia', 'GE ', 'GEO ', '268', 2),
        (54, 'Германия', 'Germany', 'DE ', 'DEU ', '276', 3),
        (79, 'Гана', 'Ghana', 'GH ', 'GHA ', '288', 1),
        (86, 'Греция', 'Greece', 'GR ', 'GRC ', '300', 3),
        (81, 'Гренландия', 'Greenland', 'GL ', 'GRL ', '304', 4),
        (75, 'Гренада', 'Grenada', 'GD ', 'GRD ', '308', 4),
        (84, 'Гваделупа', 'Guadeloupe', 'GP ', 'GLP ', '312', 4),
        (89, 'Гуам', 'Guam', 'GU ', 'GUM ', '316', 5),
        (78, 'Гернси', 'Guernsey', 'GG ', 'GGY ', '831', 3),
        (83, 'Гвинея', 'Guinea', 'GN ', 'GIN ', '324', 1),
        (90, 'Гвинея-Бисау', 'Guinea-Bissau', 'GW ', 'GNB ', '624', 1),
        (91, 'Гайана', 'Guyana', 'GY ', 'GUY ', '328', 6),
        (96, 'Гаити', 'Haiti', 'HT ', 'HTI ', '332', 4),
        (94, 'Гондурас', 'Honduras', 'HN ', 'HND ', '340', 4),
        (92, 'Гонконг', 'Hong Kong', 'HK ', 'HKG ', '344', 2),
        (97, 'Венгрия', 'Hungary', 'HU ', 'HUN ', '348', 3),
        (106, 'Исландия', 'Iceland', 'IS ', 'ISL ', '352', 3),
        (102, 'Индия', 'India', 'IN ', 'IND ', '356', 2),
        (98, 'Индонезия', 'Indonesia', 'ID ', 'IDN ', '360', 2),
        (105, 'Иран', 'Iran (Islamic Republic of)', 'IR ', 'IRN ', '364', 2),
        (104, 'Ирак', 'Iraq', 'IQ ', 'IRQ ', '368', 2),
        (99, 'Ирландия', 'Ireland', 'IE ', 'IRL ', '372', 3),
        (100, 'Израиль', 'Israel', 'IL ', 'ISR ', '376', 2),
        (107, 'Италия', 'Italy', 'IT ', 'ITA ', '380', 3),
        (108, 'Джерси', 'Jersey', 'JE ', 'JEY ', '832', 3),
        (26, 'Сен-Бартелеми', 'Saint Barthélemy', 'BL ', 'BLM ', '652', 4),
        (87, 'Южная Георгия и Южные Сандвичевы острова', 'South Georgia and the South Sandwich Islands', 'GS ', 'SGS ', '239', 7),
        (65, 'Испания', 'Spain', 'ES ', 'ESP ', '724', 3),
        (42, 'Швейцария', 'Switzerland', 'CH ', 'CHE ', '756', 3),
        (74, 'Великобритания', 'United Kingdom of Great Britain and Northern Ireland', 'GB ', 'GBR ', '826', 3),
        (6, 'Албания', 'Albania', 'AL ', 'ALB ', '8  ', 3),
        (59, 'Алжир', 'Algeria', 'DZ ', 'DZA ', '12 ', 1),
        (12, 'Американское Самоа', 'American Samoa', 'AS ', 'ASM ', '16 ', 5),
        (63, 'Западная Сахара', 'Western Sahara', 'EH ', 'ESH ', '732', 1),
        (210, 'Эсватини', 'Eswatini', 'SZ ', 'SWZ ', '748', 1),
        (109, 'Ямайка', 'Jamaica', 'JM ', 'JAM ', '388', 4),
        (111, 'Япония', 'Japan', 'JP ', 'JPN ', '392', 2),
        (110, 'Иордания', 'Jordan', 'JO ', 'JOR ', '400', 2),
        (122, 'Казахстан', 'Kazakhstan', 'KZ ', 'KAZ ', '398', 2),
        (112, 'Кения', 'Kenya', 'KE ', 'KEN ', '404', 1),
        (115, 'Кирибати', 'Kiribati', 'KI ', 'KIR ', '296', 5),
        (119, 'Южная Корея', 'Korea, Republic of', 'KR ', 'KOR ', '410', 2),
        (120, 'Кувейт', 'Kuwait', 'KW ', 'KWT ', '414', 2),
        (113, 'Киргизия', 'Kyrgyzstan', 'KG ', 'KGZ ', '417', 2),
        (123, 'Лаос', 'Lao People''s Democratic Republic', 'LA ', 'LAO ', '418', 2),
        (132, 'Латвия', 'Latvia', 'LV ', 'LVA ', '428', 3),
        (124, 'Ливан', 'Lebanon', 'LB ', 'LBN ', '422', 2),
        (129, 'Лесото', 'Lesotho', 'LS ', 'LSO ', '426', 1),
        (128, 'Либерия', 'Liberia', 'LR ', 'LBR ', '430', 1),
        (133, 'Ливия', 'Libya', 'LY ', 'LBY ', '434', 1),
        (126, 'Лихтенштейн', 'Liechtenstein', 'LI ', 'LIE ', '438', 3),
        (130, 'Литва', 'Lithuania', 'LT ', 'LTU ', '440', 3),
        (131, 'Люксембург', 'Luxembourg', 'LU ', 'LUX ', '442', 3),
        (145, 'Макао', 'Macao', 'MO ', 'MAC ', '446', 2),
        (139, 'Мадагаскар', 'Madagascar', 'MG ', 'MDG ', '450', 1),
        (153, 'Малави', 'Malawi', 'MW ', 'MWI ', '454', 1),
        (152, 'Мальдивы', 'Maldives', 'MV ', 'MDV ', '462', 2),
        (142, 'Мали', 'Mali', 'ML ', 'MLI ', '466', 1),
        (150, 'Мальта', 'Malta', 'MT ', 'MLT ', '470', 3),
        (140, 'Маршалловы о-ва', 'Marshall Islands', 'MH ', 'MHL ', '584', 5),
        (148, 'Мавритания', 'Mauritania', 'MR ', 'MRT ', '478', 1),
        (151, 'Маврикий о.', 'Mauritius', 'MU ', 'MUS ', '480', 1),
        (154, 'Мексика', 'Mexico', 'MX ', 'MEX ', '484', 4),
        (136, 'Молдавия', 'Moldova, Republic of', 'MD ', 'MDA ', '498', 3),
        (135, 'Монако', 'Monaco', 'MC ', 'MCO ', '492', 3),
        (137, 'Черногория', 'Montenegro', 'ME ', 'MNE ', '499', 3),
        (149, 'Монтсеррат', 'Montserrat', 'MS ', 'MSR ', '500', 4),
        (134, 'Марокко', 'Morocco', 'MA ', 'MAR ', '504', 1),
        (156, 'Мозамбик', 'Mozambique', 'MZ ', 'MOZ ', '508', 1),
        (143, 'Мьянма', 'Myanmar', 'MM ', 'MMR ', '104', 2),
        (166, 'Науру', 'Nauru', 'NR ', 'NRU ', '520', 5),
        (165, 'Непал', 'Nepal', 'NP ', 'NPL ', '524', 2),
        (163, 'Нидерланды', 'Netherlands', 'NL ', 'NLD ', '528', 3),
        (158, 'Новая Каледония', 'New Caledonia', 'NC ', 'NCL ', '540', 5),
        (168, 'Новая Зеландия', 'New Zealand', 'NZ ', 'NZL ', '554', 5),
        (162, 'Никарагуа', 'Nicaragua', 'NI ', 'NIC ', '558', 4),
        (159, 'Нигер', 'Niger', 'NE ', 'NER ', '562', 1),
        (167, 'Ниуэ', 'Niue', 'NU ', 'NIU ', '570', 5),
        (160, 'Остров Норфолк', 'Norfolk Island', 'NF ', 'NFK ', '574', 5),
        (141, 'Македония', 'North Macedonia', 'MK ', 'MKD ', '807', 3),
        (164, 'Норвегия', 'Norway', 'NO ', 'NOR ', '578', 3),
        (169, 'Оман', 'Oman', 'OM ', 'OMN ', '512', 2),
        (175, 'Пакистан', 'Pakistan', 'PK ', 'PAK ', '586', 2),
        (182, 'Палау', 'Palau', 'PW ', 'PLW ', '585', 5),
        (180, 'Палестина', 'Palestine, State of', 'PS ', 'PSE ', '275', 2),
        (170, 'Панама', 'Panama', 'PA ', 'PAN ', '591', 4),
        (183, 'Парагвай', 'Paraguay', 'PY ', 'PRY ', '600', 6),
        (171, 'Перу', 'Peru', 'PE ', 'PER ', '604', 6),
        (174, 'Филиппины', 'Philippines', 'PH ', 'PHL ', '608', 2),
        (178, 'о-ва Питкэрн', 'Pitcairn', 'PN ', 'PCN ', '612', 5),
        (176, 'Польша', 'Poland', 'PL ', 'POL ', '616', 3),
        (181, 'Португалия', 'Portugal', 'PT ', 'PRT ', '620', 3),
        (179, 'Пуэрто-Рико', 'Puerto Rico', 'PR ', 'PRI ', '630', 4),
        (184, 'Катар', 'Qatar', 'QA ', 'QAT ', '634', 2),
        (185, 'Реюньон', 'Réunion', 'RE ', 'REU ', '638', 1),
        (188, 'Россия', 'Russian Federation', 'RU ', 'RUS ', '643', 3),
        (189, 'Руанда', 'Rwanda', 'RW ', 'RWA ', '646', 1),
        (117, 'Сент-Китс и Невис', 'Saint Kitts and Nevis', 'KN ', 'KNA ', '659', 4),
        (125, 'Сент-Люсия', 'Saint Lucia', 'LC ', 'LCA ', '662', 4),
        (138, 'Синт-Мартен', 'Saint Martin (French part)', 'MF ', 'MAF ', '663', 4),
        (201, 'Сан-Марино', 'San Marino', 'SM ', 'SMR ', '674', 3),
        (206, 'Сан-Томе и Принсипи', 'Sao Tome and Principe', 'ST ', 'STP ', '678', 1),
        (190, 'Саудовская Аравия', 'Saudi Arabia', 'SA ', 'SAU ', '682', 2),
        (202, 'Сенегал', 'Senegal', 'SN ', 'SEN ', '686', 1),
        (187, 'Сербия', 'Serbia', 'RS ', 'SRB ', '688', 3),
        (192, 'Сейшелы', 'Seychelles', 'SC ', 'SYC ', '690', 1),
        (200, 'Сьерра-Леоне', 'Sierra Leone', 'SL ', 'SLE ', '694', 1),
        (199, 'Словакия', 'Slovakia', 'SK ', 'SVK ', '703', 3),
        (197, 'Словения', 'Slovenia', 'SI ', 'SVN ', '705', 3),
        (203, 'Сомали', 'Somalia', 'SO ', 'SOM ', '706', 1),
        (205, 'Южный Судан', 'South Sudan', 'SS ', 'SSD ', '728', 1),
        (127, 'Шри-Ланка', 'Sri Lanka', 'LK ', 'LKA ', '144', 2),
        (193, 'Судан', 'Sudan', 'SD ', 'SDN ', '729', 1),
        (204, 'Суринам', 'Suriname', 'SR ', 'SUR ', '740', 6),
        (194, 'Швеция', 'Sweden', 'SE ', 'SWE ', '752', 3),
        (209, 'Сирия', 'Syrian Arab Republic', 'SY ', 'SYR ', '760', 2),
        (216, 'Таджикистан', 'Tajikistan', 'TJ ', 'TJK ', '762', 2),
        (215, 'Тайланд', 'Thailand', 'TH ', 'THA ', '764', 2),
        (218, 'Восточный Тимор', 'Timor-Leste', 'TL ', 'TLS ', '626', 5),
        (214, 'Того', 'Togo', 'TG ', 'TGO ', '768', 1),
        (211, 'Острова Теркс и Кайкос', 'Turks and Caicos Islands', 'TC ', 'TCA ', '796', 4),
        (121, 'Острова Кайман', 'Cayman Islands', 'KY ', 'CYM ', '136', 4),
        (212, 'Чад', 'Chad', 'TD ', 'TCD ', '148', 1),
        (116, 'Коморы', 'Comoros', 'KM ', 'COM ', '174', 1),
        (233, 'Сент-Винсент и Гренадины', 'Saint Vincent and the Grenadines', 'VC ', 'VCT ', '670', 4),
        (220, 'Тунис', 'Tunisia', 'TN ', 'TUN ', '788', 1),
        (222, 'Турция', 'Turkey', 'TR ', 'TUR ', '792', 2),
        (234, 'Венесуэла', 'Venezuela (Bolivarian Republic of)', 'VE ', 'VEN ', '862', 6),
        (33, 'Остров Буве', 'Bouvet Island', 'BV ', 'BVT ', '74 ', 7),
        (103, 'Британская территория в Индийском океане', 'British Indian Ocean Territory', 'IO ', 'IOT ', '86 ', 2),
        (114, 'Камбоджа', 'Cambodia', 'KH ', 'KHM ', '116', 2),
        (254, 'Чили', 'Chile', 'CL ', 'CHL ', '152', 6),
        (39, 'ДР Конго', 'Congo, Democratic Republic of the', 'CD ', 'COD ', '180', 1),
        (53, 'Чехия', 'Czechia', 'CZ ', 'CZE ', '203', 3),
        (58, 'Доминиканская Республика', 'Dominican Republic', 'DO ', 'DOM ', '214', 4),
        (207, 'Сальвадор', 'El Salvador', 'SV ', 'SLV ', '222', 4),
        (213, 'Французские Южные и Антарктические Территории', 'French Southern Territories', 'TF ', 'ATF ', '260', 7),
        (80, 'Гибралтар', 'Gibraltar', 'GI ', 'GIB ', '292', 3),
        (88, 'Гватемала', 'Guatemala', 'GT ', 'GTM ', '320', 4),
        (93, 'Остров Херд и остров Макдональд', 'Heard Island and McDonald Islands', 'HM ', 'HMD ', '334', 7),
        (232, 'Ватикан', 'Holy See', 'VA ', 'VAT ', '336', 3),
        (101, 'о-в Мэн', 'Isle of Man', 'IM ', 'IMN ', '833', 3),
        (118, 'Корейская Народно-Демократическая Республика', 'Korea (Democratic People''s Republic of)', 'KP ', 'PRK ', '408', 2),
        (155, 'Малайзия', 'Malaysia', 'MY ', 'MYS ', '458', 2),
        (147, 'Мартиника', 'Martinique', 'MQ ', 'MTQ ', '474', 4),
        (70, 'Федеративные Штаты Микронезии', 'Micronesia (Federated States of)', 'FM ', 'FSM ', '583', 5),
        (144, 'Монголия', 'Mongolia', 'MN ', 'MNG ', '496', 2),
        (157, 'Намибия', 'Namibia', 'NA ', 'NAM ', '516', 1),
        (161, 'Нигерия', 'Nigeria', 'NG ', 'NGA ', '566', 1),
        (146, 'Северные Марианские о-ва', 'Northern Mariana Islands', 'MP ', 'MNP ', '580', 5),
        (173, 'Папуа-Новая Гвинея', 'Papua New Guinea', 'PG ', 'PNG ', '598', 5),
        (186, 'Румыния', 'Romania', 'RO ', 'ROU ', '642', 3),
        (196, 'Св. Елены, о-в', 'Saint Helena, Ascension and Tristan da Cunha', 'SH ', 'SHN ', '654', 1),
        (240, 'Самоа', 'Samoa', 'WS ', 'WSM ', '882', 5),
        (195, 'Сингапур', 'Singapore', 'SG ', 'SGP ', '702', 2),
        (191, 'Соломоновы о-ва', 'Solomon Islands', 'SB ', 'SLB ', '90 ', 5),
        (244, 'Майотта', 'South Africa', 'ZA ', 'ZAF ', '710', 1),
        (198, 'Шпицберген', 'Svalbard and Jan Mayen', 'SJ ', 'SJM ', '744', 3),
        (225, 'Тайвань', 'Taiwan, Province of China', 'TW ', 'TWN ', '158', 2),
        (226, 'Танзания', 'Tanzania, United Republic of', 'TZ ', 'TZA ', '834', 1),
        (217, 'Токелау', 'Tokelau', 'TK ', 'TKL ', '772', 5),
        (219, 'Туркменистан', 'Turkmenistan', 'TM ', 'TKM ', '795', 2),
        (224, 'Тувалу', 'Tuvalu', 'TV ', 'TUV ', '798', 5),
        (228, 'Уганда', 'Uganda', 'UG ', 'UGA ', '800', 1),
        (227, 'Украина', 'Ukraine', 'UA ', 'UKR ', '804', 3),
        (2, 'Объединенные Арабские Эмираты', 'United Arab Emirates', 'AE ', 'ARE ', '784', 2),
        (229, 'Соединенные Штаты Америки', 'United States of America', 'US ', 'USA ', '840', 4),
        (230, 'Уругвай', 'Uruguay', 'UY ', 'URY ', '858', 6),
        (231, 'Узбекистан', 'Uzbekistan', 'UZ ', 'UZB ', '860', 2),
        (237, 'Вьетнам', 'Viet Nam', 'VN ', 'VNM ', '704', 2),
        (235, 'Британские Виргинские острова', 'Virgin Islands (British)', 'VG ', 'VGB ', '92 ', 4),
        (236, 'Американские Виргинские острова', 'Virgin Islands (U.S.)', 'VI ', 'VIR ', '850', 4),
        (239, 'о-ва Уоллис и Футуна', 'Wallis and Futuna', 'WF ', 'WLF ', '876', 5),
        (242, 'Йемен', 'Yemen', 'YE ', 'YEM ', '887', 2),
        (245, 'Замбия', 'Zambia', 'ZM ', 'ZMB ', '894', 1),
        (3, 'Афганистан', 'Afghanistan', 'AF ', 'AFG ', '4  ', 2),
        (5, 'Ангилья', 'Anguilla', 'AI ', 'AIA ', '660', 4),
        (14, 'Австралия', 'Australia', 'AU ', 'AUS ', '36 ', 5),
        (19, 'Бангладеш', 'Bangladesh', 'BD ', 'BGD ', '50 ', 2),
        (69, 'Фолклендские острова', 'Falkland Islands (Malvinas)', 'FK ', 'FLK ', '238', 6),
        (172, 'Французская Полинезия', 'French Polynesia', 'PF ', 'PYF ', '258', 5),
        (177, 'Сен-Пьер и Микелон', 'Saint Pierre and Miquelon', 'PM ', 'SPM ', '666', 4),
        (221, 'Тонга', 'Tonga', 'TO ', 'TON ', '776', 5),
        (223, 'Тринидад и Тобаго', 'Trinidad and Tobago', 'TT ', 'TTO ', '780', 4),
        (238, 'Вануату', 'Vanuatu', 'VU ', 'VUT ', '548', 5),
        (246, 'Зимбабве', 'Zimbabwe', 'ZW ', 'ZWE ', '716', 1),
        (29, 'Боливия', 'Bolivia (Plurinational State of)', 'BO ', 'BOL ', '68 ', 6),
        (255, 'Абхазия', 'Abkhazia', 'AB ', 'ABH ', '895', 2);
